### ISSUE TITLE
getNext() error result

### ISSUE THREAD

**Issue by ThomasPerraudin** [poliander/cron#10]
```
$c = new \Cron('0 3 * * *');
echo $c->getNext();
```
Executed at 2022-03-30 01:55:01
Expected:

2022-03-30 03:00:00

Actual:

2022-03-30 **05**:00:00

**Comment by ThomasPerraudin** [comment]
```
$ php -i | grep timezone
Default timezone => Europe/Berlin
date.timezone => no value => no value

```

**Comment by poliander** [comment]
I'm sorry but I can't reproduce this - can you please give the actual timestamp what was returned by getNext()? With v2.4.1, the timezone will not matter anymore. The starting timestamp is GMT and the timestamp returned by getNext() is also GMT (as long as no timezone was specified via the 2nd parameter of the class constructor.

**Comment by poliander** [comment]
@ThomasPerraudin 

Feel free to add more information on how to exactly reproduce your problem (ideally as unit test or at least a reproducible code snippet), but for now I am pretty confident that the timestamp calculation actually works correct.

**Comment by ThomasPerraudin** [comment]
@poliander I made a big mistake will installing the new version of the code. The issue will probably disappear with your new version on my side now. Sorry to have bothered you stupidly !

**Comment by poliander** [comment]
@ThomasPerraudin 

No problem, you're welcome!
