### ISSUE TITLE
Date slip with getNext()

### ISSUE THREAD

**Issue by ThomasPerraudin** [poliander/cron#11]
Similar #9 

```
$c = new \Cron('0 3 * * *', new \DateTimeZone('Europe/Paris'));
echo $c->getNext();
```
___
### When run at 1649202901 //2022-04-06 01:55:01
Expected:

`1649206800 //2022-04-06 03:00:00`

Actual:

`1649206800 //2022-04-06 03:00:00` **OK**

___
### When run at 1649203201 //2022-04-06 02:00:01
Expected:

`1649206800 //2022-04-06 03:00:00`

Actual:

`1649293200 //2022-04-07 03:00:00` **ERROR**

**Comment by poliander** [comment]
Thank you for reporting the bug and providing reproducible examples. It should be finally be fixed in v2.4.2
