### ISSUE TITLE
Compatibility with last PHP version

### ISSUE THREAD

**Issue by applibs** [poliander/cron#16]
Change function parseRange to this:
Its impossible pass string $range with array.

```
private function parseRange(array &$register, int $index, string $range, int $stepping): void
    {
        if ($range === '*') {
            $rangeArr = [self::VALUE_BOUNDARIES[$index]['min'], self::VALUE_BOUNDARIES[$index]['max']];
        } else {
            $rangeArr = explode('-', $range);
        }

        $this->validateRange($rangeArr, $index);
        $this->fillRange($register, $index, $rangeArr, $stepping);
    }
```

**Comment by poliander** [comment]
Could you please give some more information on this? E.g.

- to which PHP version do you refer?
- what error occurs?
- which version is affected?

**Comment by applibs** [comment]
- PHP 8.2
- New value type (array) is not matching the resolved parameter type and might introduce types-related false-positives.

**Comment by poliander** [comment]
Thank you, I understand now. I'll do a bugfix release very soon!
