### ISSUE TITLE
[Bug] - Infinity loop

### ISSUE THREAD

**Issue by VencaKrecl** [poliander/cron#18]
Hey, 

I discovered a bug in this package. If you use `59 23 31 6 *` (the date is not valid) expression then the `getNext` ends in infinity loop.

**Comment by poliander** [comment]
Will be fixed in next 2.4/3.0 releases, thank you very much! Very nasty one, indeed.

**Comment by poliander** [comment]
Fixed in v2.4.8 and v3.0.6
