### ISSUE TITLE
Support for integers starting with zero

### ISSUE THREAD

**Issue by FrKevin** [poliander/cron#22]
Hi there, 

I found a bug with cron: `0-30/2 02,06-19 5-30/5 1-11 1-2,4-5`.

In fact this is a valid cron, but the ìsValidî method sends false.

I think I have found the origin of this error: 
![image](https://github.com/poliander/cron/assets/6602646/8446e902-6a07-4380-9fb7-6c024eafee5d)

Here we are comparing 2 and 02.

But 02 = 2 is an integer.

**Comment by poliander** [comment]
Will look into it, thank you for reporting!

**Comment by poliander** [comment]
Fixed in v2.4.9 and v3.0.7
