### ISSUE TITLE
PHP 8.4 better compatibility

### ISSUE THREAD

**Issue by vencakrecl** [poliander/cron#26]
`PHP Deprecated:  Poliander\Cron\CronExpression::__construct(): Implicitly marking parameter $timeZone as nullable is deprecated, the explicit nullable type must be used instead in poliander/cron/src/Cron/CronExpression.php on line 98
`

**Comment by vencakrecl** [comment]
https://github.com/poliander/cron/pull/27

**Comment by poliander** [comment]
Thank you very much, I will take a look at it soon(ish)

**Comment by poliander** [comment]
Merged and released in v3.2.1
