### ISSUE TITLE
Could you change the namespace to "PoliadeCron", because in laravel this name "Cron" conflicts?

### ISSUE THREAD

**Issue by jeffleyd** [poliander/cron#8]
https://github.com/poliander/cron/blob/fda892c60cd87056d1963f342f0f732b3cb2c2a0/src/Cron/CronExpression.php#L3

**Comment by poliander** [comment]
I see, Laravel 9 depends on package "dragonmantank/cron-expression" which has the same namespace an class name. But may I ask why you don't switch over to this library? Seems to be quite similiar :-)

**Comment by jeffleyd** [comment]
Because, it's a laravel dependency, so I don't have the autonomy to change it. I think you changing your name would make it easier for all your library users.

**Comment by poliander** [comment]
Well I was wondering which breaking change I could introduce to justify a v3.0.0 (just kidding). More seriously, my thinking was to release a v3.0.0 with PHPUnit 10 support and wanted to drop PHP 7 support then. This should be somewhere around in the first half of February. Would that timeframe be okay for you?

**Comment by jeffleyd** [comment]
> Because, it's a laravel dependency, so I don't have the autonomy to change it. I think you changing your name would make it easier for all your library users.



> 

This is very good for me, I'll be waiting for the changes. 
Thanks a lot!

**Comment by jeffleyd** [comment]
> Well I was wondering which breaking change I could introduce to justify a v3.0.0 (just kidding). More seriously, my thinking was to release a v3.0.0 with PHPUnit 10 support and wanted to drop PHP 7 support then. This should be somewhere around in the first half of February. Would that timeframe be okay for you?

This is very good for me, I'll be waiting for the changes.
Thanks a lot!

**Comment by poliander** [comment]
Okay, I'll leave this issue open until then. Thank you for reporting the namespace/classname conflict!

**Comment by poliander** [comment]
Nah, not yet, I was hoping for a PHPUnit 10 release this February to justify a v3.0 release with changed namespace, but I think I will do so this week anyway.

**Comment by poliander** [comment]
Sorry for the delay, but I really wanted to wait for the next PHPUnit release. However, I just released a v3.0.0 (identical to latest v2.4) with an updated namespace.
